name: Add Branch Type Label

on:
  pull_request:
    types: opened

jobs:
  SetLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Set labels
        uses: woocommerce/grow/packages/js/github-actions/actions/branch-label@add/label-action